language: node_js
node_js:
  - "7"
deploy:
  provider: heroku
  api_key: $heroku_api_key
  branches:
    only:
    - master
  install:
    - node-sass-chokidar src/ -o src/
  script:
    - npm run build